import React from 'react'
import'./About.css'

function About() {
  return (
    <div className='main-container-about'>
      <div className='text-container'>jfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjd</div>
    </div>
  )
}

export default About
