import React from 'react'
import styles from './About.css'

function About() {
  return (
    <div className='main-container'>
      <div className='text-container'>jfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjdjfljlsdjfjd</div>
    </div>
  )
}

export default About
